name: Build NRO

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/switchdev:latest

    steps:
      - uses: actions/checkout@v4

      - name: Compilar
        env:
          DEVKITPRO: /opt/devkitpro
          DEVKITA64: /opt/devkitpro/devkitA64
        run: |
          make clean
          make

      - name: Subir artifact
        uses: actions/upload-artifact@v4
        with:
          name: switch-updater
          path: switch-updater.nro
