name: Build Docker Image

on:
  push:
    paths:
      - 'Dockerfile'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Login en GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construir y subir imagen
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/thewizwikii/switch-builder:latest
